services:
  sranalysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sranalysis
    restart: unless-stopped
    ports:
      - "3005:3000"
    networks:
      - sranalysis-network

networks:
  sranalysis-network:
    driver: bridge
